# Generated by Django 5.2.3 on 2025-08-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='deuda_otro',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='porcentaje_otro',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='porcentaje_pagador',
        ),
    ]
