# Generated by Django 5.2.3 on 2025-08-21 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gasto_deuda_otro_remove_gasto_porcentaje_otro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='deuda_otro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gasto',
            name='porcentaje_otro',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='gasto',
            name='porcentaje_pagador',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
