# Generated by Django 5.2.3 on 2025-08-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gasto_deuda_otro_gasto_porcentaje_otro_and_more'),
    ]

    operations = [
    ]
