# Generated by Django 5.2.3 on 2025-08-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250821_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='deuda_otro',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='porcentaje_otro',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='porcentaje_pagador',
        ),
    ]
