# Generated by Django 5.2.3 on 2025-08-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_gasto_deuda_otro_remove_gasto_porcentaje_otro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('Gastos piso', 'Gastos piso'), ('Supermercado', 'Supermercado'), ('Viajes', 'Viajes'), ('Ocio', 'Ocio'), ('Otros', 'Otros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
