# Generated by Django 5.2.3 on 2025-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_gasto_options_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Supermercado'), ('2', 'Viajes'), ('3', 'Gastos piso'), ('4', 'Ocio'), ('5', 'Otros')], max_length=20),
        ),
    ]
