# Generated by Django 5.2.3 on 2025-08-22 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_gasto_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FondoComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTOS', 'Gastos del piso'), ('COMPRAS', 'Compras del piso'), ('VIAJES', 'Fondo para viajes'), ('AHORRO', 'Ahorro de pareja')], max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fondo común',
                'verbose_name_plural': 'Fondos comunes',
            },
        ),
        migrations.CreateModel(
            name='IngresoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fondocomun')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso a fondo',
                'verbose_name_plural': 'Ingresos a fondos',
            },
        ),
    ]
