# Generated by Django 5.2.3 on 2025-08-22 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fondocomun_ingresofondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fondocomun'),
        ),
    ]
