# Generated by Django 5.2.3 on 2025-08-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_gasto_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondocomun',
            name='tipo',
            field=models.CharField(choices=[('GASTOS', 'Gastos del piso'), ('COMPRAS', 'Compras del piso'), ('VIAJES', 'Fondo para viajes'), ('AHORRO', 'Ahorro de pareja'), ('SUPERMERCADO', 'Supermercado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Supermercado'), ('2', 'Viajes'), ('3', 'Gastos piso'), ('4', 'Ocio'), ('5', 'Otros'), ('6', 'Compras piso')], max_length=20),
        ),
    ]
