# Generated by Django 5.2.3 on 2025-09-12 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_fondocomun_tipo_alter_gasto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10)),
                ('categoria', models.CharField(choices=[('1', 'Supermercado'), ('2', 'Viajes'), ('3', 'Gastos piso'), ('4', 'Ocio'), ('5', 'Otros'), ('6', 'Compras piso')], default='5', max_length=20)),
                ('prorratear', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_ano_aplicado', models.IntegerField(blank=True, null=True)),
                ('ultimo_mes_aplicado', models.IntegerField(blank=True, null=True)),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fondocomun')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aporte_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_ano_aplicado', models.IntegerField(blank=True, null=True)),
                ('ultimo_mes_aplicado', models.IntegerField(blank=True, null=True)),
                ('fondo_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fondocomun')),
            ],
        ),
    ]
