# Generated by Django 5.2.3 on 2025-09-12 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_gastorecurrente_objetivoahorro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingresofondo',
            options={},
        ),
        migrations.AddField(
            model_name='ingresofondo',
            name='es_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingresofondo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
